name: hello-node-snap # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple node hello snap
description: |
  Simple snap build to hello a node simple app. Interesting example to test 
  with different node.js versions!

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable # devel / must be 'stable' to release into candidate/stable channels
confinement: strict # 'devmode' / 'strict' once you have the right plugs and slots

apps:
  hello:
    command: bin/hello

parts:
  hello-node:
    source: .
    plugin: npm
    npm-node-version: '16.10.0'
    override-build: |
      npm config set unsafe-perm true
    #  npm install -g --prefix $SNAPCRAFT_PART_BUILD


